### ISSUE TITLE
Documentation doesn't include information about how to use SessionProvider restorePreviousSession

### ISSUE THREAD

**Issue by alastair** [inrupt/solid-ui-react#395]
hi!

### Search terms you've used
restorePreviousSession

### Feature suggestion

The documentation for this package at https://solid-ui-react.docs.inrupt.com/?path=/story/usage--page doesn't show any examples about how to use the restorePreviousSession or onSessionRestore props to `<SessionProvider>`. 

I had found the documentation at https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/restore-session-browser-refresh/ about the core "restore" functionality, and was trying to implement it myself.
It wasn't until I read the source at https://github.com/inrupt/solid-ui-react/blob/main/src/context/sessionContext/index.tsx that I realised that there was a stub implementation already there.

### Actual functionality/enhancement

I recommend to add an example to the library examples, perhaps with an example of restoring a route using nextjs or react router to show developers how to re-login the user and redirect back to the initially loaded url.

**Comment by kevin-inrupt** [comment]
Hi @alastair,

Thanks for the feedback on the `solid-ui-react` documentation. I have notified our documentation team, and they will address in an upcoming sprint. Once the documentation has been updated, we will let you know via this issue.

Thanks again.

Kevin
Inrupt Support

**Comment by andydavison** [comment]
Hi @alastair,

It turns out the component example in Storybook at https://solid-ui-react.docs.inrupt.com/?path=/docs/authentication-session-provider--provider-with-hook did already include the basic usage of those props, but a bug with our Storybook setup was stopping that 'Show code' preview from working properly.

That's now resolved in the latest release, along with adding descriptions of those two props to the table below - hopefully that makes things clearer. Thanks again for the feedback!

**Comment by alastair** [comment]
great, thanks @andydavison
